### PR TITLE
Allow to set hook callbacks in the JWT claims.

### PR DESCRIPTION
**Pull request by calavera**
- An identity provider can set default URL endpoints with them.
- Use the configuration URL if it exists.
- Fallback to JWT claims only if the configuration doesn't explicitly set a URL.

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by brycekahle** [comment]
I don't see where the `function_hooks` is being set when the claims are generated, only where they are consumed.

**Comment by calavera** [comment]
@brycekahle those hooks are added to the token by the identity service. They are not set here

**Comment by brycekahle** [comment]
I'm confused, gotrue normally issues the tokens since it has the secret.

**Comment by calavera** [comment]
> I'm confused, gotrue normally issues the tokens since it has the secret.
@brycekahle sorry, I meant to put it in the signature, not the user token. Check the last commit out.

**Pull request merged**
