### PR TITLE
Add www

### PR DESCRIPTION
**Pull request by eliwilliamson**
**- Summary**

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by brycekahle** [comment]
Whoa, why so many commits?

**Comment by brycekahle** [comment]
Also, this is going from `master` -> `add-www`. If you want I can rebase that branch and we don't need this PR?

**Comment by eliwilliamson** [comment]
this was built ages ago but never merged - the rebase looped in all the commits from then to now

**Comment by eliwilliamson** [comment]
it is going `add-www` -> `master`

**Comment by brycekahle** [comment]
> wants to merge 239 commits into add-www from master

**Pull request closed without merging**
