### PR TITLE
Update x/crypto

### PR DESCRIPTION
**Pull request by jenae-janzen**
**- Summary**
Fixes: https://github.com/netlify/gotrue/security/dependabot/25

**- Test plan**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by jenae-janzen** [comment]
@rybit, I was wondering if you had any suggestions here -- 
Initially, all the checks were failing. I updated the go version, which seemed to help, but now I'm seeing
Screenshot 2024-12-17 at 12 19 55 PM

When I ran `go mod tidy`, the version of `golang.org/x/net` was set to `v0.25.0`. I tried following the instructions in the error message and resetting it to `v0.21.0`, but every time I run `go mod tidy` it sets it back to `v0.25.0`. Do you have any ideas how to work around this?

**Comment by rybit** [comment]
I suspect that the problem is you're building with 1.15 & 1.16: https://github.com/netlify/gotrue/blob/master/.github/workflows/test.yaml#L12

**Comment by jenae-janzen** [comment]
@rybit, you were spot on about the tests building with the wrong version! It seems like now I'm stuck on the same problem Ramon was having in [this pr](https://github.com/netlify/gotrue/pull/367), where triggering circleci by calling `https://circleci.com/api/v2/project/gh/netlify/gotrue-ci/pipeline` is failing

**Comment by jenae-janzen** [comment]
@rybit ah, I'm not sure why I thought that, but for some reason it seems like the test (1.15.x) step is required to merge, and looking in the `test.yaml` file there's this block:
```
      - name: Trigger CircleCI for deployment
        if: ${{ (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == 'netlify/gotrue') && matrix.go-version == '1.15.x' }}
        run: |
          curl -X POST --silent --show-error --fail \
            -H 'Circle-Token: ${{ secrets.CIRCLE_TOKEN }}' \
            -H 'content-type: application/json' \
            --data '{ "branch": "master", "parameters": { "branch": "${{ github.event.pull_request.head.ref || github.ref_name }}", "commit": "${{ github.event.pull_request.head.sha || github.sha }}" } }' \
            https://circleci.com/api/v2/project/gh/netlify/gotrue-ci/pipeline
   ```
            
I tried switching it to run for 1.22 instead, but that's when I saw 
Screenshot 2024-12-18 at 11 30 19 AM

**Comment by rybit** [comment]
I removed the 1.15x requirement and changed it to 1.22. I'm betting that check is so that we can trigger the internal deployment mechanism in that repo. Worth maybe figuring out what those calls are for. idk if you need to make like a matching branch in that repo.

**Review by rybit — APPROVED** [review]

**Comment by jenae-janzen** [comment]
Thanks for all your help @rybit!!

**Pull request merged**
