### PR TITLE
feat: add microsoft provider

### LINKED ISSUE #216: Add Microsoft as an external provider
**- Do you want to request a *feature* or report a *bug*?**

A feature. An addition to the list of supported providers

**- What is the current behavior?**

Current providers are very developer-centric

**- What is the expected behavior?**

Implement Microsoft as an external provider, using the [golang.org/x/oauth2/microsoft](https://godoc.org/golang.org/x/oauth2/microsoft) package.

### PR DESCRIPTION
**Pull request by JamieMagee**
**- Summary**

Fixes #216 

NOTE: It's not possible to get an avatar URL, only the actual binary data for the avatar.

Useful documentation:
- https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent
- https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints
- https://docs.microsoft.com/en-gb/graph/api/user-get?view=graph-rest-1.0&tabs=http
- https://developer.microsoft.com/en-us/graph/graph-explorer/preview

**- Test plan**

Still TODO. Not 100% sure how to test this, and would appreciate any input here

**- Description for the changelog**

Initial implementation of Microsoft identity provider

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by JamieMagee** [comment]
@kitop @mraerino Can I get this reviewed? Or if not you, who should I ping about this?

**Comment by mraerino** [comment]
hey, we don't have a lot of bandwidth on the team for this right now.

I noticed there are no tests. can you add some?

**Comment by JamieMagee** [comment]
@kitop @mraerino If I rebase this, do you have bandwidth to review it?

**Review by rybit — COMMENTED** [review]
The overall changes look good! One minor note.

Have you managed to run this locally and see if it works as you expect with microsoft? A lot of integrations are...hairy.

**Comment by tlsimm** [comment]
@kitop I see this is still requiring some approvals - is this something we want still want to support?

**Comment by kitop** [comment]
This will fall under @rjbeers team, so he should be weighing in.

**Comment by tlsimm** [comment]
Can this be closed out?

**Comment by JamieMagee** [comment]
Closing this out. If you want to add this functionality, backport it from the supabase port[^1]

[^1]: https://github.com/supabase/gotrue/blob/master/api/provider/azure.go

**Pull request closed without merging**
