### PR TITLE
reduce docker image size

### PR DESCRIPTION
**Pull request by tpiskula**
**- Summary**
First, thanks for open-sourcing this! 
I noticed the docker image is based on golang:1.8.3-stretch, 
which is resulting in an image size of **1.28GB** !
- Is there any reason you ship the complete build environment with the image?

I have created a multi-stage Dockerfile, basing the final on alpine, 
that brought down the image size to **25.3MB**

**- Test plan**
bildschirmfoto 2017-09-09 um 13 11 45

I have started both containers with sqllite driver and tested all endpoints with postman
bildschirmfoto 2017-09-09 um 13 37 56

**- Description for the changelog**
added  multi-stage docker build to reduce image size

**- A picture of a cute animal (not mandatory but encouraged)**
My cat chillin
img_6115

### CODE REVIEW

**Comment by calavera** [comment]
My only concern about this change is that it will require a very up to date version of Docker, which might not work in some environments. I would be ok replacing the whole docker file with a different version that completely depends on alpine without doing multi stage processing.

**Comment by brycekahle** [comment]
Docker multi-stage builds were added in 17.05 and our build pipeline runs 17.06.

**Comment by tpiskula** [comment]
@calavera i agree, the build should work with older docker versions too.
basing the image on alpine would help reduce size, but we would still ship build dependencies with the final image. Another possibility would be to use 2 dockerfiles, one for building and production.

**Comment by calavera** [comment]
> Docker multi-stage builds were added in 17.05 and our build pipeline runs 17.06.

Based on that comment, I'm ok merging this. Thanks @tpiskula !

**Comment by tpiskula** [comment]
no problem @calavera! I have now reverted the last view commits 👍

**Comment by brycekahle** [comment]
I wonder if we should do a static build (with `CGO_ENABLED=0`), so we don't have to worry about musl C linking issues?

**Comment by tpiskula** [comment]
@brycekahle I tried building with CGO_ENABLED=0 and no musl in the dockerfile.
Unfortunately mattn/go-sqlite3 depends on cgo, I was able to run the container with the postgres driver, using the sqlite3 driver causes gotrue to crash.

**Comment by brycekahle** [comment]
This got addressed in #141 

Thanks for your help!

**Comment by goodforever** [comment]
@tpiskula How to config for postgres , what driver package did you import ?

**Pull request closed without merging**
