### PR TITLE
create webhook for signup flow

### PR DESCRIPTION
**Pull request by rybit**
This creates a webhook that is part of the signup flow. If configured it will notify an external service and allow it to verify the contents.

### CODE REVIEW

**Comment by rybit** [comment]
@biilmann I am not sure what data you wanted in the hook, but this is a good starting point?

**Comment by calavera** [comment]
I'd put the name of the event in the payload and the user model, something like this:

```
{
  "event": "signup",
  "user": {
  ...
}
```

**Comment by rybit** [comment]
To get the user model, I'd have to make it in the DB. I thought we would want the hook to have us not even make the user if it fails. I can add the user metadata though.

**Comment by rybit** [comment]
Wait. I totally lied. I misread the code.

**Comment by calavera** [comment]
@rybit can the webhook be set via the API, we'll need to set this from the UI?

**Comment by calavera** [comment]
LGTM

**Pull request merged**
